after-login-command = []
after-startup-command = []
start-at-login = true
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false
accordion-padding = 20
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']
 
[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        10
outer.right =      10

[mode.main.binding]
ctrl-period = 'layout tiles horizontal vertical'
ctrl-comma = 'layout accordion horizontal vertical'

cmd-left = 'focus left'
cmd-down = 'focus down'
cmd-up = 'focus up'
cmd-right = 'focus right'

cmd-shift-left = 'move left'
cmd-shift-down = 'move down'
cmd-shift-up = 'move up'
cmd-shift-right = 'move right'

cmd-shift-minus = 'resize smart -50'
cmd-shift-equal = 'resize smart +50'
cmd-shift-space = 'fullscreen' 

cmd-ctrl-left = ['join-with left', 'mode main']
cmd-ctrl-down = ['join-with down', 'mode main']
cmd-ctrl-up = ['join-with up', 'mode main']
cmd-ctrl-right = ['join-with right', 'mode main']
cmd-ctrl-f = ['layout floating tiling', 'mode main'] 

cmd-alt-right = 'workspace --wrap-around next'
cmd-alt-left = 'workspace --wrap-around prev'

#Monitor 1 left hand
alt-a = 'workspace a'
alt-o = 'workspace o'
alt-e = 'workspace e'
alt-u = 'workspace u'
cmd-alt-a = 'move-node-to-workspace a'
cmd-alt-o = 'move-node-to-workspace o'
cmd-alt-e = 'move-node-to-workspace e'
cmd-alt-u = 'move-node-to-workspace u'
#Monitor 2 left hand
alt-q = 'workspace q'
alt-j = 'workspace j'
alt-k = 'workspace k'
cmd-alt-q = 'move-node-to-workspace q'
cmd-alt-j = 'move-node-to-workspace j'
cmd-alt-k = 'move-node-to-workspace k'
#Monitor 1 right hand
alt-h = 'workspace h'
alt-t = 'workspace t'
alt-n = 'workspace n'
alt-s = 'workspace s'
cmd-alt-h = 'move-node-to-workspace h'
cmd-alt-t = 'move-node-to-workspace t'
cmd-alt-n = 'move-node-to-workspace n'
cmd-alt-s = 'move-node-to-workspace s'
#Monitor 2 right hand
alt-m = 'workspace m'
alt-w = 'workspace w'
alt-v = 'workspace v'
cmd-alt-m = 'move-node-to-workspace m'
cmd-alt-w = 'move-node-to-workspace w'
cmd-alt-v = 'move-node-to-workspace v'

alt-tab = 'workspace-back-and-forth'
cmd-alt-tab = 'move-workspace-to-monitor --wrap-around next'
ctrl-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
backspace = ['close-all-windows-but-current', 'mode main']
