start-at-login = true

after-login-command = []
after-startup-command = [
     'exec-and-forget /opt/homebrew/opt/sketchybar/bin/sketchybar',
  'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
]
exec-on-workspace-change = [
  '/bin/bash',
  '-c',
  'sketchybar --trigger workspace_changed CURRENT=$AEROSPACE_FOCUSED_WORKSPACE PREVIOUS=$AEROSPACE_PREV_WORKSPACE'
]

on-focused-monitor-changed = [
  'move-mouse monitor-lazy-center'
]

on-focus-changed = [
  'move-mouse window-lazy-center',
  'exec-and-forget /opt/homebrew/bin/sketchybar --trigger front_app_switched',
  'exec-and-forget sketchybar --trigger update_windows'
]

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false
accordion-padding = 20
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
 
[gaps]
inner.horizontal = 5
inner.vertical =   5
outer.left =       0
outer.bottom =     0
outer.top =        0#[{monitor.'^built-in retina display$' = 20 }, 52]
outer.right =      0

[mode.main.binding]
ctrl-period = 'layout tiles horizontal vertical'
ctrl-comma = 'layout accordion horizontal vertical'

cmd-left = 'focus left'
cmd-down = 'focus down'
cmd-up = 'focus up'
cmd-right = 'focus right'

cmd-shift-left = 'move left'
cmd-shift-down = 'move down'
cmd-shift-up = 'move up'
cmd-shift-right = 'move right'

cmd-shift-minus = 'resize smart -50'
cmd-shift-equal = 'resize smart +50'
cmd-shift-space = 'fullscreen' 

cmd-alt-left = ['join-with left', 'mode main']
cmd-alt-down = ['join-with down', 'mode main']
cmd-alt-up = ['join-with up', 'mode main']
cmd-alt-right = ['join-with right', 'mode main']
cmd-alt-f = ['layout floating tiling', 'mode main'] 

cmd-ctrl-right = 'workspace --wrap-around next'
cmd-ctrl-left = 'workspace --wrap-around prev'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'

alt-0 = 'workspace-back-and-forth'
alt-shift-0 = 'move-workspace-to-monitor --wrap-around next'
ctrl-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
backspace = ['close-all-windows-but-current', 'mode main']
